#define DOUBLE_COLON_CONCAT(Y, X) Y:: X

#define DOUBLE_COLON_CONCAT_HELPER(x, y)\
  DOUBLE_COLON_CONCAT_EXECUTE(DOUBLE_COLON_CONCAT, x, y)

#define DOUBLE_COLON_CONCAT_EXECUTE(CONCATENATE, x, y)\
  CONCATENATE(x, y)
